### ISSUE TITLE
对idf 版本要求 (AIV-576)

### ISSUE THREAD

**Issue by weilian1977** [espressif/esp-dl#111]
目前支持什么版本的idf？

**Comment by Sandra-lol** [comment]
For setup instructions to get started with ESP-DL, please read [Get Started](https://github.com/espressif/esp-dl/blob/master/docs/en/get_started.md).

Please use the [release/v4.4](https://github.com/espressif/esp-idf/tree/release/v4.4) ESP-IDF on master branch.

**Comment by real-hao** [comment]
何时支持idf - v5.0

**Comment by Auroragan** [comment]
请查看分支 idfv5.0
