### ISSUE TITLE
esp32s3 recognizer undefine function (AIV-579)

### ISSUE THREAD

**Issue by ajtwlsdlqp** [espressif/esp-dl#112]
Hi,
I tried to porting esp32-s3-eye example to my target board 
target board also same esp32s3 N8R8
so, i need your help.

Eclipse (2022-09 (4.25.0)) 
ESP-IDF 4.4.3
ESP32S3-N8R8

human face detection, color detection, move detection are working well on my board,
but when i try to add recognition, i got this type error

d:/develop_tool/espressif/tools/xtensa-esp32s3-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32s3-elf/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: 
my_Proj_Path\libmfn.a(mfn112_1x_model_s8.cpp.obj): in function `int* std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<int>(int const*, int const*, int*)':
/home/yuanjiong/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-8.4.0/xtensa-esp32s3-elf/xtensa-esp32s3-elf/include/c++/8.4.0/bits/stl_algobase.h:368: undefined reference to `dl::nn::add2d(dl::Tensor<signed char>&, dl::Tensor<signed char>&, dl::Tensor<signed char>&, dl::Activation<signed char> const*, std::vector<int, std::allocator<int> > const&, int)'

there are no error when i try to include header files
![image](https://user-images.githubusercontent.com/10431571/217737063-25fea3b4-742d-41d6-85aa-8377902e2464.png)

my partition tble
![image](https://user-images.githubusercontent.com/10431571/217737217-e98f6478-ffd7-4f5d-b438-6b01e95f7fdb.png)

i thinks build size also enough
![image](https://user-images.githubusercontent.com/10431571/217737680-7b4f7958-0f76-4ee9-9848-b13b995fb1e5.png)

i add esp-dl to submodule and i have that static library
![image](https://user-images.githubusercontent.com/10431571/217737894-9b068b2a-6ac5-491c-b260-eb7f4c932210.png)

when i call
#if CONFIG_MFN_V1
#if CONFIG_S8
    FaceRecognition112V1S8 *recognizer = new FaceRecognition112V1S8();
#elif CONFIG_S16
    FaceRecognition112V1S16 *recognizer = new FaceRecognition112V1S16();
#endif
#endif

this function that error came out..

Thanks, 
Best Regards

**Comment by Auroragan** [comment]
Hi,
Can you run the origin example https://github.com/espressif/esp-dl/tree/master/examples/face_recognition successfully?

**Comment by ajtwlsdlqp** [comment]
Hi, Thanks for reply
now i'm try that example to upload

![image](https://user-images.githubusercontent.com/10431571/217758175-b13c8f69-023f-451e-ab6b-df2559fa4368.png)

![image](https://user-images.githubusercontent.com/10431571/217758267-162e099f-8ae2-4f93-902a-b3bee49498d7.png)

![image](https://user-images.githubusercontent.com/10431571/217758847-bf68f85c-2578-496a-9edc-28ea3f326d2e.png)


there are some warning (looks purple color ) but it's working well 
my target board has no lcd to check it so i try terminal version

**Comment by ajtwlsdlqp** [comment]
solved. 
not a bug
