### ISSUE TITLE
猫脸侦测的模型训练 (AIV-581)

### ISSUE THREAD

**Issue by AlexHsuYu** [espressif/esp-dl#113]
请问猫脸侦测是采用什么模型进行训练，另外有猫脸侦测的模型训练流程与模型转换部分的范例吗?  感谢

**Comment by Auroragan** [comment]
Hi,
这个模型是乐鑫自研的模型，猫脸的示例是没有的
转换可以参考https://github.com/espressif/esp-dl/tree/master/tutorial/quantization_tool_example，步骤是一样的
