### ISSUE TITLE
请问想做物体检测，推荐什么模型好饿 (AIV-597)

### ISSUE THREAD

**Issue by BILLY-JB** [espressif/esp-dl#118]
本人新手，想检测物体，就像例子的人脸，猫脸，能提供他们怎么训练的例子吗？只是想训练自己的希望识别的物体，或者推荐使用的训练模型吗？
本来用了YOLOV5训练了，然后根据你们的步骤，看生成处理的onnx，有100多层。。好多，想着手写model_define.hpp太恐怖了

**Comment by sun-xiangyu** [comment]
可以尝试新的ESP-DL,支持自动模型加载和构图，不再需要手动添加每一层
