### ISSUE TITLE
运行/tools/quantization_tool/examples/example.py 报错MatMul算子在esp-dl上不支持 (AIV-599)

### ISSUE THREAD

**Issue by junnan-xjtu** [espressif/esp-dl#120]
报错信息：
Generating the quantization table:
MatMul is not supported on esp-dl yet
Traceback (most recent call last):
  File "example.py", line 38, in <module>
    calib.generate_quantization_table(model_proto, calib_dataset, pickle_file_path)
  File "calibrator.py", line 344, in calibrator.Calibrator.generate_quantization_table
  File "calibrator.py", line 231, in calibrator.Calibrator.generate_output_model
  File "calibrator.py", line 226, in calibrator.Calibrator.check_model
ValueError: current model is not supported by esp-dl

**Comment by junnan-xjtu** [comment]
请问这是什么原因造成的，代码没有改动过

**Comment by Raven888888** [comment]
Did you face this problem during setup? #121

**Comment by Auroragan** [comment]
Hi, example.py 中会调用 optimized_model_path = optimize_fp_model(model_path) 这个函数来将 matmul 转为 gemm，函数定义在 https://github.com/espressif/esp-dl/blob/master/tools/quantization_tool/optimizer.py，检查一下路径之类的有没有问题吧

**Comment by zhouayi** [comment]
我也出现了同样的问题，然后我原本的环境是python=3.7，onnx=1.13.1。然后我将onnx降低版本为1.9.0后，问题解决了
![github](https://github.com/espressif/esp-dl/assets/54144475/2a6a2d27-7825-4a1c-9e3c-0dd8d4f670b8)
