### ISSUE TITLE
[need help] about examples in ESP-DL (AIV-621)

### ISSUE THREAD

**Issue by fatsheep2020** [espressif/esp-dl#125]
here my 2 question:
1. the examples "cat_face_detect", "color_detect", ..., was running in ESP32, not see what's the model details, how to know that?
(例子中的模型是开源的吗，哪里有介绍吗？)

2. for a specific use case, how to setup/train a model target for ESP32S3? what's  the constraint? 
(针对ESP32建立、训练模型有哪些限制（模型太大肯定跑不动），有哪些需要注意的地方？ 请乐鑫技术人员给解释一下吧，这样便于我们开发人员做二次开发）

THanks!

**Comment by sun-xiangyu** [comment]
请使用新版esp-dl, 里面有开源的模型示例
