### ISSUE TITLE
人脸检测 (AIV-629)

### ISSUE THREAD

**Issue by Liuyuehuixue** [espressif/esp-dl#127]
人脸检测示例中，第二次更换image图片，idf.py  flash monitor报错。
build 过程报错：region `drom0_0_seg' overflowed by 975180 bytes collect2.exe: error: ld returned 1 exit status ninja: build stopped: subcommand failed.想重复更换自定义的示例图片，这个问题如何解决呢？

**Comment by Auroragan** [comment]
Hi
你是把 https://github.com/espressif/esp-dl/blob/master/examples/human_face_detect/main/image.hpp 里面的 IMAGE_ELEMENT 替换掉了吗

**Comment by Liuyuehuixue** [comment]
你好，是的，将image替换后运行python脚本，更换了image.hpp。
更换esp32s3, 修改图片size现在问题已经解决了。
