### ISSUE TITLE
TVM generated code is not correct (output_data.h) (AIV-635)

### ISSUE THREAD

**Issue by Farzinkh** [espressif/esp-dl#128]
Hi, thank you for adding this TVM feature. However, I think the generated code is not what it is supposed to be. Can you help me to tackle this problem? 
output_data.h  content:                   
`#include <tvmgen_default.h>
const size_t output_len = 10;
const static __attribute__((aligned(16))) float output_data[10]
={};
`
The ONNX model I am trying is for the classification of the MNIST dataset with only 2 Dense layers.
And I found another problem in `export_onnx_model.py`
changing [line 12](https://github.com/espressif/esp-dl/blob/b6783aee63f6486939956b5f27eca5d88f90cd2c/tools/tvm/export_onnx_model.py#L12) to:
`esp_dl_library_path = os.environ["ESP_DL_PATH"]+'/'`
This will solve the error of not finding files when calling this script in another one.

**Comment by Auroragan** [comment]
Hi,
Could you give more info about: 'the generated code is not what it is supposed to be'? What is your expected result?

And thanks for the advice.

**Comment by Farzinkh** [comment]
Hi,
I don't even know How in the first place I was capable of running `export_onnx_model` currently I am receiving this error
`esp-dl/tools/tvm/python/tvm/relay/ty.py", line 26, in <module>
    Any = _ffi_api.Any
AttributeError: module 'tvm.relay._ffi_api' has no attribute 'Any'
`
