### ISSUE TITLE
FAILED: esp32-template-project.elf (AIV-636)

### ISSUE THREAD

**Issue by cuiyong127** [espressif/esp-dl#129]
![image](https://github.com/espressif/esp-dl/assets/11641348/649a24af-ab36-4944-a3fd-4ec8836b4db1)

**Comment by cuiyong127** [comment]
你好，我使用tvm生成了一个工程，但是在esp32板端编译的时候产生了如上错误信息，请问如何解决？

**Comment by zhouayi** [comment]
我也遇到同样的问题，请问你解决了吗？

**Comment by BlueSkyB** [comment]
看IDF版本，貌似用的还是IDF4.4？目前的esp-dl需要使用IDF-5.0，可以用这个IDF版本再试一下
