### ISSUE TITLE
Upload esp-dl to IDF Component Registry (AIV-647)

### ISSUE THREAD

**Issue by tore-espressif** [espressif/esp-dl#135]
Hello @Auroragan 
I can see that this is a IDF component with already implemented `idf_component.yml`. Do you plan to upload it to [IDF Component Registry](https://components.espressif.com/)?

Let me know if you need any help, I can push a GH workflow that will do this automatically for you.
Cheers, Tomas

**Comment by Auroragan** [comment]
Hi Tomas,
Yeah we're interested in doing that, but I don't have any experience with the upload process. If you could help with the workflow, that would be great.
