### ISSUE TITLE
In-place crop_and_resize (AIV-650)

### ISSUE THREAD

**Issue by eloquentarduino** [espressif/esp-dl#137]
I see `crop_and_resize` can be used to both crop and resize an image. I want to use it to resize in-place a rgb565 frame from my camera. This is what I'd like to achieve:

 - capture images in JPEG at high resolution (e.g. 640x480)
 - convert to 1/8th  RGB565 using `jpg2rgb565(frame->buf, frame->len, rgb565, JPG_SCALE_8X)`
 - crop `dest` to square using the following:

```
crop_and_resize(
  dst_image=rgb565,
  dst_width=100, 
  dst_channel=3, 
  dst_y_start=0,
  dst_y_end=0,
  dst_x_start=0,
  dst_x_end=0,
  src_image=rgb565,
  src_height=480,
  src_width=640,
  src_channel=3,
  src_y_start=0,
  src_y_end=480,
  src_x_start=(640 - 480) / 2,
  src_x_end=(640 - 480) / 2 + 480
 )
```

Will this work?
I want to avoid allocating a new array of size 100x100 to store the resized image.

**Comment by Sandra-lol** [comment]
Hi, looks like it won't work, because decompression is not streaming, which means it does not allow in-place decoding.
