### ISSUE TITLE
Allow using esp-dl with esp-idf v5.1 and newer (AIV-658)

### ISSUE THREAD

**Issue by adokitkat** [espressif/esp-dl#142]
I tried using esp-dl with latest master branch of esp-idf and it worked OK when I changed the version restriction in [idf_component.yml](https://github.com/espressif/esp-dl/blob/master/idf_component.yml).  Don't restrict using new versions, instead show a warning to use recommended version.

**Comment by Ilidur** [comment]
I submitted a PR to enable this as an external user. Hopefully it can be reviewed soon.
https://github.com/espressif/esp-dl/pull/144

**Comment by BlueSkyB** [comment]
@Ilidur The PR has been merged. Thank you for submitting the revised code.
