### ISSUE TITLE
 How to save face ID to sdcard instead of flash (AIV-669)

### ISSUE THREAD

**Issue by MichaelDu9226** [espressif/esp-dl#148]
https://github.com/espressif/esp-dl/blob/79034eeb6a98e5dd896c1bf8e87403d562460078/include/model_zoo/face_recognizer.hpp

According to the code, currently, face id data can only be saved in Flash storage.

 How to save face ID to sdcard instead of flash

**Comment by sun-xiangyu** [comment]
@MichaelDu9226 , please try new esp-dl. Now we can save face ID to sdcard.
