### ISSUE TITLE
Evalutor only supports esp32s3? (AIV-671)

### ISSUE THREAD

**Issue by Oreobird** [espressif/esp-dl#149]
Using latest code from master branch and quantizing model for esp32, got the error below:
> Generating the quantization table:
> Converting coefficient to int8 per-tensor quantization for esp32
> Exporting finish, the output files are: /content/drive/MyDrive/hand_recognition//trained_model//coefficient.cpp, /content/drive/MyDrive/hand_recognition//trained_model//coefficient.hpp
> 
> Quantized model info:
> model input name: conv2d_input, exponent: -7
> Reshape layer name: StatefulPartitionedCall/sequential/conv2d/BiasAdd__6, output_exponent: -7
> Conv layer name: StatefulPartitionedCall/sequential/conv2d/BiasAdd, output_exponent: -8
> MaxPool layer name: StatefulPartitionedCall/sequential/max_pooling2d/MaxPool, output_exponent: -8
> Conv layer name: StatefulPartitionedCall/sequential/conv2d_1/BiasAdd, output_exponent: -8
> MaxPool layer name: StatefulPartitionedCall/sequential/max_pooling2d_1/MaxPool, output_exponent: -8
> Conv layer name: StatefulPartitionedCall/sequential/conv2d_2/BiasAdd, output_exponent: -8
> MaxPool layer name: StatefulPartitionedCall/sequential/max_pooling2d_2/MaxPool, output_exponent: -8
> Transpose layer name: StatefulPartitionedCall/sequential/max_pooling2d_2/MaxPool__28, output_exponent: -8
> Reshape layer name: StatefulPartitionedCall/sequential/flatten/Reshape, output_exponent: -8
> Gemm layer name: fused_gemm_0, output_exponent: -9
> Gemm layer name: fused_gemm_1, output_exponent: -9
> Softmax layer name: StatefulPartitionedCall/sequential/dense_1/Softmax, output_exponent: -9
> 
> Evaluating the performance on esp32:
> Traceback (most recent call last):
>   File "//content/drive/MyDrive/hand_recognition//esp_dl_quant.py", line 153, in <module>
>     'minmax' if args.calib_method is None else args.calib_method)
>   File "//content/drive/MyDrive/hand_recognition//esp_dl_quant.py", line 61, in quantize
>     eva = evaluator.Evaluator(bw, granularity, target)
>   File "evaluator.py", line 32, in evaluator.Evaluator.__init__
> ValueError: currently only supports `esp32s3`, while received esp32

Evalutor only supports  esp32s3?

**Comment by BlueSkyB** [comment]
Yes, it's only supports esp32s3
