### ISSUE TITLE
ESP-DL TVM: UnboundLocalError: local variable 'bias_add' referenced before assignment (AIV-674)

### ISSUE THREAD

**Issue by MichelBerg** [espressif/esp-dl#151]
During some experiments while using ESP-DL TVM I faced the following Error:

`**UnboundLocalError: local variable 'bias_add' referenced before assignment**`
https://github.com/espressif/esp-dl/blob/6933e459e6099f110a590f08cc9454306e54fc74/tools/tvm/python/tvm/relay/op/contrib/esp.py#L138C1-L161C17

I dont have deep knowledge within this code, but I was able to bypass the error by setting `bias_add = pattern`, to make sure the variable is available.

Someone with prior knowledge should take care of it.

**Comment by BlueSkyB** [comment]
We have fixed this issue, you can try it again now. The commit is: 19d377e
