### ISSUE TITLE
custom model with TVM deployment error  function 'TVMGetLastPythonError' not found (AIV-685)

### ISSUE THREAD

**Issue by Cilouche** [espressif/esp-dl#157]
Hi,

I'm trying to create a custom model for detection, I follow this tutorial 
 https://docs.espressif.com/projects/esp-dl/en/latest/esp32s3/tutorials/deploying-models-through-tvm.html,
 I use conda under windows for a development environment, when I try to deploy my solution on an esp32s3 I encounter a problem with TVM, namely that I have performed all the installation steps the error below

![image](https://github.com/espressif/esp-dl/assets/48053323/73be7ec4-516d-47af-aa93-f9b9a2e39c37)

Any suggestion please ?

**Comment by sun-xiangyu** [comment]
Subsequent versions will no longer support TVM, please use the new version esp-dl
