### ISSUE TITLE
Latency of Face Recognition (AIV-689)

### ISSUE THREAD

**Issue by assman** [espressif/esp-dl#160]
The docs say that the latency for a 16bit S3 is more than that of an 8bit S3? Is it for real or is there a mistake here?
<img width="1109" alt="Screenshot 2024-03-29 at 3 39 32 PM" src="https://github.com/espressif/esp-dl/assets/14093665/fefd5513-d5da-4729-a6ee-603391194cd0">

**Comment by MichelBerg** [comment]
Why should it be a mistake? As it says, the int8 model has a smaller footprint and shorter latency. Think about having approximate half the data compared to the int16 model, it has to be faster.
