### ISSUE TITLE
直接运行examples face_recognition报错 undefined reference to `void dl::image::warp_affine<short>(dl::Tensor<short>*, dl::Tensor<short>*, dl::math::Matrix<float>*)' (AIV-699)

### ISSUE THREAD

**Issue by SindenDev** [espressif/esp-dl#165]
FAILED: face_recognition.elf 
cmd.exe /C "cd . && D:\Espressif\tools\xtensa-esp-elf\esp-13.2.0_20230928\xtensa-esp-elf\bin\xtensa-esp32s3-elf-g++.exe -mlongcalls  -fno-builtin-memcpy -fno-builtin-memset -fno-builtin-bzero -fno-builtin-stpcpy -fno-builtin-strncpy -Wl,--cref -Wl,--defsym=IDF_TARGET_ESP32S3=0 -Wl,--Map=E:/Work/github.com/esp-dl/examples/face_recognition/build/face_recognition.map -Wl,--no-warn-rwx-segments -fno-rtti -fno-lto -Wl,--gc-sections -Wl,--warn-common -T esp32s3.peripherals.ld -T esp32s3.rom.ld -T esp32s3.rom.api.ld -T esp32s3.rom.libgcc.ld -T esp32s3.rom.newlib.ld -T esp32s3.rom.version.ld -T memory.ld -T sections.ld @CMakeFiles\face_recognition.elf.rsp -o face_recognition.elf  && cd ."
D:/Espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld.exe: E:/Work/github.com/esp-dl/examples/face_recognition/main/../../../lib/esp32s3\libmfn.a(face_recognition_tool.cpp.obj):(.literal._ZN21face_recognition_tool10align_faceIsEEvPN2dl6TensorIT_EES5_RSt6vectorIiSaIiEE[_ZN21face_recognition_tool10align_faceIsEEvPN2dl6TensorIT_EES5_RSt6vectorIiSaIiEE]+0x0): undefined reference to `void dl::image::warp_affine<short>(dl::Tensor<short>*, dl::Tensor<short>*, dl::math::Matrix<float>*)'
D:/Espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld.exe: E:/Work/github.com/esp-dl/examples/face_recognition/main/../../../lib/esp32s3\libmfn.a(face_recognition_tool.cpp.obj): in function `void face_recognition_tool::align_face<short>(dl::Tensor<short>*, dl::Tensor<short>*, std::vector<int, std::allocator<int> >&)':
/home/gansichen/Workspace/delete/aigit/master/dl/components/mfn/face_recognition_tool.cpp:251:(.text._ZN21face_recognition_tool10align_faceIsEEvPN2dl6TensorIT_EES5_RSt6vectorIiSaIiEE[_ZN21face_recognition_tool10align_faceIsEEvPN2dl6TensorIT_EES5_RSt6vectorIiSaIiEE]+0x192): undefined reference to `void dl::image::warp_affine<short>(dl::Tensor<short>*, dl::Tensor<short>*, dl::math::Matrix<float>*)'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by BlueSkyB** [comment]
目前IDF可以支持到IDF 5.1，更高的IDF版本暂时还没有做支持
