### ISSUE TITLE
When will face recognition be available on the ESP32-P4? (AIV-715)

### ISSUE THREAD

**Issue by mootterry** [espressif/esp-dl#175]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Described the feature in detail and justified the reason for the request.
- [x] Provided specific use cases and examples.

### Feature description

When will face recognition be available on the ESP32-P4, like it was on the ESP32-S3?

### Use cases

none

**Comment by 100312dog** [comment]
@mootterry We're working on this. It should be available at the end of this month. We'll first update the basic interface for face recognition in esp-dl, then we'll update the full example in esp-who.

**Comment by sun-xiangyu** [comment]
@100312dog , now  face recognition is available on esp32p4, please try.

**Comment by LeandroLuquetta** [comment]
Hello, can you provide a link to the esp32p4 face recognition?

**Comment by sun-xiangyu** [comment]
example: https://github.com/espressif/esp-dl/tree/master/examples/human_face_recognition
model: https://github.com/espressif/esp-dl/tree/master/models/human_face_recognition
