### ISSUE TITLE
Pedestrian Detection Network type (AIV-727)

### ISSUE THREAD

**Issue by simoberny** [espressif/esp-dl#181]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Provided a clear description of your suggestion.
- [X] Included any relevant context or examples.

### Issue or Suggestion Description

Hi,
Would it be possible to know the type of network used in the Pedestrian Detection example? It performs well with good accuracy. I am considering using a similar network for a comparable application but with customized training.

Thank you in advance for your help.
Best regards

**Comment by 100312dog** [comment]
@simoberny 
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.8/configs/picodet
It is a modified version of picodet.

**Comment by simoberny** [comment]
> [@simoberny](https://github.com/simoberny) https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.8/configs/picodet 

Would it be possible to get more details on how to reproduce the network? I'd like to train a similar custom model.

Currently, I'm trying with a PicoDet XS network, but I'm encountering some issues with ONNX export. Specifically, I can't use Opset 11 due to the presence of HardSwish as the activation function.

Thanks in advance!
