### ISSUE TITLE
ESP-dl support doc missing (AIV-730)

### ISSUE THREAD

**Issue by acse-hz923** [espressif/esp-dl#184]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Described the feature in detail and justified the reason for the request.
- [X] Provided specific use cases and examples.

### Feature description

I think the support doc of ESP-dl is missing as I open the page it turns out 404

### Use cases

support doc

**Comment by BlueSkyB** [comment]
Due to iterative updates to the ESP-DL architecture, we have updated all the documentation as well. The documentation link is here: https://docs.espressif.com/projects/esp-dl/en/latest/how_to_load_model.html. I just tried it and it opens; could you please give it a try?

**Comment by acse-hz923** [comment]
Thank you!
