### ISSUE TITLE
how to use esp32 to detect other object?

### ISSUE THREAD

**Issue by xpdrycry** [espressif/esp-dl#28]
We want to use esp32 to detect other image recognition, such as text, please ask, how should this be trained? Based on the model you provided,

**Comment by yehangyang** [comment]
Hi, @xpdrycry 

Sorry, we do not support that. Probably, you can train your own model and deploy it on esp32 with ESP-DL.
About how to customize your own model, please check the temporary branch [esp-dl/v2_ahpha](https://github.com/espressif/esp-dl/tree/v2_alpha).

Best Regards.
