### ISSUE TITLE
About face detection and face recognition

### ISSUE THREAD

**Issue by Rita858** [espressif/esp-dl#30]
Hi,
I just wonder: 
1. Where is the "face id vectors" exactly store in [CameraWebServer](https://github.com/espressif/arduino-esp32/tree/master/libraries/ESP32/examples/Camera/CameraWebServer)? (flash or RAM?)
2. And how many face id can it store?
3. Does face recognition use a one-to-one comparison to get the owner of the face or a one-to-many(face id) method to find the person?
4. What is the value of FR and FA?
5. How long does it take on face detection? What about face recognition? 

I am new about this.
Hope to get your help soon.
Thank you.

**Comment by TiramisuJ** [comment]
Hi
1. In CameraWebServer, The face id vectors are stored in RAM.
2. You can set the maximum number of face IDs that can be stored, in the CameraWebServer, you can set the 'FACE_ID_SAVE_NUMBER' in 'app_httpd.cpp'.
3. The face recognition will compare the face information that has been enrolled so far.
4. Sorry i didn't understand this question. FD and FR mean face detection and face recognition respectively.
5. You can refer to [face_detection](https://github.com/espressif/esp-face/blob/master/face_detection/README.md) and [face_recognition](https://github.com/espressif/esp-face/blob/master/face_recognition/README.md) for more details.

**Comment by Rita-GE** [comment]
> Hi
> 
> 1. In CameraWebServer, The face id vectors are stored in RAM.
> 2. You can set the maximum number of face IDs that can be stored, in the CameraWebServer, you can set the 'FACE_ID_SAVE_NUMBER' in 'app_httpd.cpp'.
> 3. The face recognition will compare the face information that has been enrolled so far.
> 4. Sorry i didn't understand this question. FD and FR mean face detection and face recognition respectively.
> 5. You can refer to [face_detection](https://github.com/espressif/esp-face/blob/master/face_detection/README.md) and [face_recognition](https://github.com/espressif/esp-face/blob/master/face_recognition/README.md) for more details.

Great, thank you.
By the way, FR means false acceptance rate and FA means false rejection rate. 
Can you tell me their values?

**Comment by TiramisuJ** [comment]
1. FAR and FRR are not independent of each other, and the relationship between them can be represented by the ROC curve. For different test sets, the ROC curve of our model is also different. The FRR corresponding to a fixed FAR under a specific test set may be a more reasonable performance indicator.
2. ‘EYE_DIST_SET' is a parameter that we used for face alignment before, and it is used to indicate the distance between the two eyes of the aligned face. But we have adopted a new face alignment method, and no longer use the ‘EYE_DIST_SET’ parameter.

**Comment by Rita-GE** [comment]
> 1. FAR and FRR are not independent of each other, and the relationship between them can be represented by the ROC curve. For different test sets, the ROC curve of our model is also different. The FRR corresponding to a fixed FAR under a specific test set may be a more reasonable performance indicator.
> 2. ‘EYE_DIST_SET' is a parameter that we used for face alignment before, and it is used to indicate the distance between the two eyes of the aligned face. But we have adopted a new face alignment method, and no longer use the ‘EYE_DIST_SET’ parameter.

Then, does “FACE_ID_SIZE” mean the size of "The face id vectors"?

**Comment by TiramisuJ** [comment]
> > 1. FAR and FRR are not independent of each other, and the relationship between them can be represented by the ROC curve. For different test sets, the ROC curve of our model is also different. The FRR corresponding to a fixed FAR under a specific test set may be a more reasonable performance indicator.
> > 2. ‘EYE_DIST_SET' is a parameter that we used for face alignment before, and it is used to indicate the distance between the two eyes of the aligned face. But we have adopted a new face alignment method, and no longer use the ‘EYE_DIST_SET’ parameter.
> 
> Then, could you tell me that does “FACE_ID_SIZE” means the size of "The face id vectors"?
> Or what is the fixed max size of "The face id vectors"?

‘FACE_ID_SIZE’ is the length of each face vector. This value depends on the face recognition model. At present, the length of the face vector obtained by our model is 512.

**Comment by Rita-GE** [comment]
> > > 1. FAR and FRR are not independent of each other, and the relationship between them can be represented by the ROC curve. For different test sets, the ROC curve of our model is also different. The FRR corresponding to a fixed FAR under a specific test set may be a more reasonable performance indicator.
> > > 2. ‘EYE_DIST_SET' is a parameter that we used for face alignment before, and it is used to indicate the distance between the two eyes of the aligned face. But we have adopted a new face alignment method, and no longer use the ‘EYE_DIST_SET’ parameter.
> > 
> > 
> > Then, could you tell me that does “FACE_ID_SIZE” means the size of "The face id vectors"?
> > Or what is the fixed max size of "The face id vectors"?
> 
> ‘FACE_ID_SIZE’ is the length of each face vector. This value depends on the face recognition model. At present, the length of the face vector obtained by our model is 512.

How many faces can it detect in a frame?

**Comment by Rita-GE** [comment]
Hi, it's been a long time.
I'm here to bother you again.

When I test the size of the new face ID, there is a strange result below:
![image](https://user-images.githubusercontent.com/53596746/90002039-b402bb00-dcc4-11ea-9a08-a953df4f0060.png)
I remember that you said that the size is 512.

This is my code below:
```
Serial.printf("Enrolled Face ID: %d\n", id_list.tail);
Serial.printf("Enrolled Face ID Size: %d\n", sizeof(id_list.id_list[id_list.tail]));
Serial.printf("Enrolled Face ID list Size: %d\n", sizeof(id_list));
```
Did I do it wrong?
And how can I get it?

Hope to receive your answer soon.
Thank you!

**Comment by TiramisuJ** [comment]
1. ‘id_list.id_list[id_list.tail])’ is a pointer to a 'dl_matrix3d_t' structure，so the size of the pointer is 4, and the face vector with a length of 512 is stored in the 'dl_matrix3d_t' structure.
2. 'id_list' is a 'face_id_list' structure, the size of the 'dl_matrix3d_t **' is 4, So this structure is 4 bytes aligned, and the size of 'face_id_list' structure is 12.

**Comment by Rita-GE** [comment]
So nice you are.Thank you.
Finally, I got that size.

TiramisuJ <notifications@github.com> 于2020年8月12日周三 下午8:55写道：

**Comment by Rita-GE** [comment]
> 1. ‘id_list.id_list[id_list.tail])’ is a pointer to a 'dl_matrix3d_t' structure，so the size of the pointer is 4, and the face vector with a length of 512 is stored in the 'dl_matrix3d_t' structure.
> 2. 'id_list' is a 'face_id_list' structure, the size of the 'dl_matrix3d_t **' is 4, So this structure is 4 bytes aligned, and the size of 'face_id_list' structure is 12.

So nice you are.Thank you.
Finally, I got that size.

**Comment by kr817** [comment]
> > 1. “ id_list.id_list [id_list.tail]）”是指向“ dl_matrix3d_t”结构的指针，因此该指针的大小为4，长度为512的面部向量存储在“ dl_matrix3d_t”结构中。
> > 2. 'id_list'是'face_id_list'结构，'dl_matrix3d_t **'的大小为4，因此此结构是4个字节对齐的，而'face_id_list'结构的大小是12。
> 
> 太好了，谢谢。
> 终于，我得到了那个尺寸。



> > 1. ‘id_list.id_list[id_list.tail])’ is a pointer to a 'dl_matrix3d_t' structure，so the size of the pointer is 4, and the face vector with a length of 512 is stored in the 'dl_matrix3d_t' structure.
> > 2. 'id_list' is a 'face_id_list' structure, the size of the 'dl_matrix3d_t **' is 4, So this structure is 4 bytes aligned, and the size of 'face_id_list' structure is 12.
> 
> So nice you are.Thank you.
> Finally, I got that size.



> > 1. ‘id_list.id_list[id_list.tail])’ is a pointer to a 'dl_matrix3d_t' structure，so the size of the pointer is 4, and the face vector with a length of 512 is stored in the 'dl_matrix3d_t' structure.
> > 2. 'id_list' is a 'face_id_list' structure, the size of the 'dl_matrix3d_t **' is 4, So this structure is 4 bytes aligned, and the size of 'face_id_list' structure is 12.
> 
> So nice you are.Thank you.
> Finally, I got that size.

How did you get that size？

**Comment by kr817** [comment]
> > 1. ‘id_list.id_list[id_list.tail])’ is a pointer to a 'dl_matrix3d_t' structure，so the size of the pointer is 4, and the face vector with a length of 512 is stored in the 'dl_matrix3d_t' structure.
> > 2. 'id_list' is a 'face_id_list' structure, the size of the 'dl_matrix3d_t **' is 4, So this structure is 4 bytes aligned, and the size of 'face_id_list' structure is 12.
> 
> So nice you are.Thank you.
> Finally, I got that size.

How did you get that size
