### ISSUE TITLE
Import pre-trained model

### ISSUE THREAD

**Issue by noukee** [espressif/esp-dl#34]
I want to make enroll from profile picture saved on database. My approach sends "face-id" by mqtt and make recognition in the backend with a pre-trained model.

In Tensorflow is available MobileNetV2 model, how can I load this pre-trained model?

**Comment by TiramisuJ** [comment]
First, you should know the structure and forward process of the model, and then convert the parameters of each layer into NPY files. [Here](https://github.com/espressif/esp-face/blob/master/tutorial/implement_your_own_model.ipynb) is a tutorial.
