### ISSUE TITLE
How to store enrolled faces on MYSQL? (AIV-398)

### ISSUE THREAD

**Issue by kr817** [espressif/esp-dl#36]

**Comment by kr817** [comment]
I have achieved it

**Comment by eesati** [comment]
@kr817  Nice job, can you help me with that, at least if you can share how you get the face id and assign it after fetching. 
I appreciate your help very much. 

Thank you

**Comment by yehangyang** [comment]
Hi @kr817,

Please close the issue, if it has been solved.
