### ISSUE TITLE
更新esp-dl后，出现了编译错误

### ISSUE THREAD

**Issue by xiao-mb** [espressif/esp-dl#51]
更新esp-dl后，出现了如下编译错误：
In file included from ../main/app_recon_process.cpp:22:
../components/esp-dl/include/image/dl_image.hpp:9:10: fatal error: dl_math_matrix.hpp: No such file or directory
 #include "dl_math_matrix.hpp"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by TiramisuJ** [comment]
你的CMakeLists.txt中的include_dirs有添加include/math 吗？ “dl_math_matrix.hpp” 在include/math 这个文件夹下

**Comment by xiao-mb** [comment]
在CMakeLists.txt 加了set(COMPONENT_REQUIRES esp-dl)，还需要在include_dirs有添加include/math 吗？

**Comment by TiramisuJ** [comment]
你可以在esp-dl 下的CMakeLists.txt 中 添加include/math，再试试看？  我们会在下一版中修复这个问题。

**Comment by xiao-mb** [comment]
可以了

**Comment by TiramisuJ** [comment]
好的～
