### ISSUE TITLE
esp32-s2 和 esp32-s3 对比 (AIV-406)

### ISSUE THREAD

**Issue by jjhuangAmba666** [espressif/esp-dl#55]
esp32-s3比esp32-s2多一个32-bit LX7，主频都是240Mhz，为什么esp32-s3运行速度比s2快近7.5倍？

**Comment by Auroragan** [comment]
Hi,

esp32-s3 上新增了向量指令对 AI 操作进行加速, 而 s2 上并没有这些加速指令
