### ISSUE TITLE
.pickle 文件生成 (AIV-407)

### ISSUE THREAD

**Issue by xiao-mb** [espressif/esp-dl#56]
能否提供一下数据集存为.pickle文件的示例代码？我在生成.pickle 时遇到了tensorflow.python.framework.errors_impl.InternalError: Tensorflow type 21 not convertible to numpy dtype.的错误。

**Comment by Auroragan** [comment]
数据集并没有规定要存在 .pickle里,  calib_dataset 的类型是 ndarray, 你能提供 ndarray 就可以了

**Comment by PureHing** [comment]
@Auroragan 你好 这里的每一张图片shape 需要保持和模型输入一致吗？

**Comment by Auroragan** [comment]
@PureHing 跟 onnx 模型输入一致, 我们没有额外加操作
