### ISSUE TITLE
模型开发部署教程 (AIV-431)

### ISSUE THREAD

**Issue by jjhuangAmba666** [espressif/esp-dl#68]
请问有一个教程，从构建模型，到训练，量化，部署 全面讲解的？

**Comment by Auroragan** [comment]
模型的构建和训练: 请根据你选用的平台从网上搜索相关资料
量化: 请参考 https://github.com/espressif/esp-dl/blob/master/tools/quantization_tool/README_cn.md
部署: 请参考 https://github.com/espressif/esp-dl/blob/master/tutorial/README_cn.md
