### ISSUE TITLE
esp32-s3-devkitc-1  guru meditation human_face_detect example (AIV-435)

### ISSUE THREAD

**Issue by cosismo** [espressif/esp-dl#69]
esp32-s3-devkitc-1
chip revision: 0
ESP-IDF v4.4-dev-3235-g3e370c4296

I got the following log after flashing the human_face_detect example:
It is IDF, DL or hardware related? 

Rebooting...
��ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x403757ac
0x403757ac: esp_restart_noos at /home/foo/esp/esp-idf/components/esp_system/port/soc/esp32s3/system_internal.c:143 (discriminator 1)

SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd0108,len:0x1858
load:0x403b6000,len:0xb74
load:0x403ba000,len:0x3010
entry 0x403b61ec
I (29) boot: ESP-IDF v4.4-dev-3235-g3e370c4296 2nd stage bootloader
I (29) boot: compile time 23:55:26
I (29) boot: chip revision: 0
I (32) qio_mode: Enabling default flash chip QIO
I (38) boot.esp32s3: Boot SPI Speed : 80MHz
I (42) boot.esp32s3: SPI Mode       : QIO
I (47) boot.esp32s3: SPI Flash Size : 4MB
I (52) boot: Enabling RNG early entropy source...
W (57) bootloader_random: RNG for ESP32-S3 not currently supported
I (64) boot: Partition Table:
I (68) boot: ## Label            Usage          Type ST Offset   Length
I (75) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (83) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (90) boot:  2 factory          factory app      00 00 00010000 00200000
I (97) boot: End of partition table
I (102) esp_image: segment 0: paddr=00010020 vaddr=3c070020 size=f1284h (987780) map
I (260) esp_image: segment 1: paddr=001012ac vaddr=3fc90ef0 size=027e0h ( 10208) load
I (262) esp_image: segment 2: paddr=00103a94 vaddr=40374000 size=0c584h ( 50564) load
I (275) esp_image: segment 3: paddr=00110020 vaddr=42000020 size=6eac4h (453316) map
I (344) esp_image: segment 4: paddr=0017eaec vaddr=40380584 size=00968h (  2408) load
I (345) esp_image: segment 5: paddr=0017f45c vaddr=50000000 size=00010h (    16) load
I (355) boot: Loaded app from partition at offset 0x10000
I (356) boot: Disabling RNG early entropy source...
W (362) bootloader_random: RNG for ESP32-S3 not currently supported
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x42006338  PS      : 0x00060930  A0      : 0x820063c9  A1      : 0x3fceb220  
0x42006338: psram_set_op_mode at /home/foo/esp/esp-idf/components/esp_hw_support/port/esp32s3/spiram_psram.c:135

A2      : 0x00000001  A3      : 0x60002000  A4      : 0x00000001  A5      : 0x03ffffff  
A6      : 0x00000000  A7      : 0x80000000  A8      : 0x8200632c  A9      : 0x3fceb200  
A10     : 0x60002000  A11     : 0x80008000  A12     : 0x00000001  A13     : 0x00000000  
A14     : 0x00000003  A15     : 0x00000003  SAR     : 0x00000008  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000009  LBEG    : 0x40056f5c  LEND    : 0x40056f72  LCOUNT  : 0x00000000  

Backtrace:0x42006335:0x3fceb2200x420063c6:0x3fceb240 0x42006443:0x3fceb290 0x403764be:0x3fceb2d0 0x42006230:0x3fceb2f0 0x40375360:0x3fceb310 0x403bb168:0x3fceb340 0x403bb5d1:0x3fceb380 0x403b6255:0x3fceb4b0 0x40045c01:0x3fceb570  |<-CORRUPTED
0x42006335: psram_set_op_mode at /home/foo/esp/esp-idf/components/esp_hw_support/port/esp32s3/spiram_psram.c:135

0x420063c6: psram_exec_cmd at /home/foo/esp/esp-idf/components/esp_hw_support/port/esp32s3/spiram_psram.c:174

0x42006443: psram_disable_qio_mode at /home/foo/esp/esp-idf/components/esp_hw_support/port/esp32s3/spiram_psram.c:188

0x403764be: psram_enable at /home/foo/esp/esp-idf/components/esp_hw_support/port/esp32s3/spiram_psram.c:355

0x42006230: esp_spiram_init at /home/foo/esp/esp-idf/components/esp_hw_support/port/esp32s3/spiram.c:231

0x40375360: call_start_cpu0 at /home/foo/esp/esp-idf/components/esp_system/port/cpu_start.c:393

**Comment by TiramisuJ** [comment]
Hi, this bug has been fixed in esp-idf, pull the idf master,  try again. make sure you have removed the build folder of the esp-dl example before you rebuilding it.

**Comment by 9305128621** [comment]
sir if we externally add camera in esp32s3 devkitC-1 board then do the face detection program

is it possible or not

Thankyou sir

**Comment by 9305128621** [comment]
Sir if is it possible then send me its camera configuration and which board I select

Thankyou sir
Prabhat Kumar Yadav

**Comment by liminghui-sandra** [comment]
Hello Prabhat,
You may need this camera converter board:
https://docs.espressif.com/projects/esp-idf/zh_CN/latest/esp32s2/hw-reference/esp32s2/user-guide-esp-lyrap-cam-v1.1.html
Check the GPIO of ESP32-S3 chip, and suggest to use the shortest Dupont wires you can find, with equal-length, for connection between boards.

**Comment by prabhu012** [comment]
Sir when I flash the code it going to flash but it not connect with wifi


[flash.txt](https://github.com/espressif/esp-dl/files/8921035/flash.txt)

**Comment by prabhu012** [comment]
and when I monitor this showing this
[monitor.txt](https://github.com/espressif/esp-dl/files/8921088/monitor.txt)

**Comment by prabhu012** [comment]
tell me about this wifi configuration

() Camera Host Name
() WiFi STA SSID
() WiFi STA Password
(ESP32-Camera) WiFi AP SSID
() WiFi AP Password
(1) Maximal STA connections
() WiFi AP Channel
(192.168.4.1) WiFi AP IP Address
(5) Maximum retry

**Comment by mehmethekim** [comment]
I can confirm that unchecking Component config--->ESP PSRAM---> Support for external , SPI-connected RAM works.
Is there a more elegant way of doing this?
Also, can you make this the default setting for the examples please until it works fine.
