### ISSUE TITLE
如何将该库移植到已有工程中？ (AIV-450)

### ISSUE THREAD

**Issue by strongerux** [espressif/esp-dl#73]

**Comment by yehangyang** [comment]
可将 esp-dl 作为已有项目的组件。可参考 [esp-who](https://github.com/espressif/esp-who)。

**Comment by strongerux** [comment]
比如我需要将哪些文件放在esp-idf的哪个位置？是否有这样的引导？因为似乎环境变量的包含是通过export.bat实现的，应该需要把库文件放在指定路径下才能识别吧。

**Comment by yehangyang** [comment]
esp-dl 不是一定要放在 esp-idf 中的。我们已经为 esp-dl 配置好作为组件的 CMake。参考 [esp-who](https://github.com/espressif/esp-who)，将 esp-dl 加入 component，并在具体项目的 CMake 里进行配置即可，如[这样](https://github.com/espressif/esp-who/blob/013561615c99f78ac7fad216e4d66daa146ac409/examples/human_face_detection/lcd/CMakeLists.txt#L5)。

**Comment by strongerux** [comment]
如果把它整个放在esp-idf/component目录下也可以吗？

**Comment by yehangyang** [comment]
也可以

**Comment by strongerux** [comment]
现在出现了一个新问题，我的模型输入是一维的传感器数据，这将导致转换失败，是否还没有适配一维数据？

**Comment by strongerux** [comment]
Traceback (most recent call last):
  File "A:/AiThinker/workspace/esp-dl/tools/quantization_tool/step2.py", line 13, in <module>
    optimizer.optimize_fp_model('model.onnx')
  File "A:\AiThinker\workspace\esp-dl\tools\quantization_tool\optimizer.py", line 149, in optimize_fp_model
    model_proto = convert_model_batch_to_dynamic(model_proto)
  File "A:\AiThinker\workspace\esp-dl\tools\quantization_tool\optimizer.py", line 139, in convert_model_batch_to_dynamic
    model = shape_inference.infer_shapes(model)
  File "A:\python3.7\lib\site-packages\onnx\shape_inference.py", line 37, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str, check_type, strict_mode)
RuntimeError: input 1 is out of bounds
报错信息以上。

**Comment by yehangyang** [comment]
目前还不支持一维数据，不过你可以尝试用二维的接口来实现一维的操作。

**Comment by strongerux** [comment]
好的，最后一个问题，example中的模块读取不到
![image](https://user-images.githubusercontent.com/66321452/139839858-b403521b-8c47-471d-b4f0-c325c1575eb4.png)

**Comment by yehangyang** [comment]
请你在什么系统下运行的，目前仅支持 windows 和 linux，python 版本 3.7

**Comment by strongerux** [comment]
python3.7.3 windows10

**Comment by yehangyang** [comment]
有尝试运行吗？

**Comment by strongerux** [comment]
运行提示找不到模块

**Comment by Auroragan** [comment]
是在 examples 目录下运行的吗？ conda 环境吗？

**Comment by Auroragan** [comment]
> RuntimeError: input 1 is out of bounds

关于这个错，方便提供一下模型吗？

**Comment by strongerux** [comment]
没装conda
模型以下
[model.zip](https://github.com/espressif/esp-dl/files/7465339/model.zip)

**Comment by Auroragan** [comment]
建议用 conda 试试

https://github.com/espressif/esp-dl/blob/master/tools/quantization_tool/optimizer.py#L135 改成这样就不会报错了
```
# model.opset_import[0].version = 13

# if not dim[0].dim_param:
dim[0].dim_param = 'N'
```

但是这个模型看起来很冗余，你的原始模型是什么格式的？

**Comment by strongerux** [comment]
好像是.h5转的，好久以前整的了，K210上能用，准备在ESP32上做点工作所以拿来试试。

**Comment by Auroragan** [comment]
目前看来这个图需要手动修改才能用 quantization_tool 进行量化，像很多squeeze, unsqueeze 节点其实都没有必要
或者用别的方法确定量化因子后用 convert_tool 直接转参数，可能还方便一些

**Comment by strongerux** [comment]
convert_tool这里提到.npy文件，这个文件是哪来的啊？

**Comment by Auroragan** [comment]
自行将模型每层的参数保存成相应 npy 文件
可以阅读一下 https://github.com/espressif/esp-dl/blob/master/tools/convert_tool/specification_of_config_json_cn.md

**Comment by strongerux** [comment]
了解了，感觉属实是有些繁琐了，TFLM现在还能用吗？

**Comment by Auroragan** [comment]
TFLM 目前不是我们在维护
