### ISSUE TITLE
Wrong comparison in Mul2D layer (AIV-479)

### ISSUE THREAD

**Issue by michalber** [espressif/esp-dl#83]
In [Mul2D layer](https://github.com/espressif/esp-dl/blob/master/include/layer/dl_layer_mul2d.hpp#L78) there is bug in wrong comparison in if statement.

Problem:
```cpp
if (this->output != NULL)
{
    this->output = new Tensor<feature_t>;
}
```

Solution:
```cpp
if (this->output == NULL)
{
    this->output = new Tensor<feature_t>;
}
```

**Comment by TiramisuJ** [comment]
The bugs have been fixed
