### ISSUE TITLE
Problem with template function nn::mul2d (AIV-480)

### ISSUE THREAD

**Issue by michalber** [espressif/esp-dl#84]
When using Mul2D layer there is compile error in running [nn:mul2d function](https://github.com/espressif/esp-dl/blob/master/include/layer/dl_layer_mul2d.hpp#L143). I am using C++17, with ESP32. Problem is occuring either when creating layer with `inplace` option or without. Tried to comment [`if constexpr` statement](https://github.com/espressif/esp-dl/blob/master/include/nn/dl_nn_mul2d.hpp#L71) but it didn't help.

```cpp
no matching function for call to 'mul2d<true>(dl::Tensor<short int>&, dl::Tensor<short int>&, dl::Tensor<short int>&, const dl::Activation<short int>*&, const std::vector<int>&)'
```

I will edit this issue if I found cause of this bug.

EDIT:
Solution:
I compared Mul2D to Add2D layer and found solution. There is wrong use of
`nn::mul2d<true>(*this->output, input0, input1, this->activation, assign_core);`

Instead you should write
`nn::mul2d(*this->output, input0, input1, this->activation, assign_core, this->output_exponent);`
or
`nn::mul2d<true>(this->output_exponent, input0, input1, this->activation, assign_core);`

but the second approach seems to be slower

**Comment by TiramisuJ** [comment]
1. Thank you for your feedback, we will fix the bugs soon.
2. `nn::mul2d<true>(this->output_exponent, input0, input1, this->activation, assign_core);` 
this function will malloc the output tensor, and return it. so this approach is slower

**Comment by TiramisuJ** [comment]
The bugs have been fixed
