### ISSUE TITLE
esp_dl的人脸识别，保存的识别人脸信息删除指定 (AIV-518)

### ISSUE THREAD

**Issue by Spring641** [espressif/esp-dl#92]
esp_dl的 who_human_face_recognition 的人脸识别，录入的ID是否可以删除指定的ID，而不是删除最后一个ID，或者能否开出一个删除指定ID的函数接口

**Comment by yehangyang** [comment]
@Spring641, 请查看这个[接口](https://github.com/espressif/esp-dl/blob/d9493506707c0b68fa10447ec24380af6f19bb32/include/model_zoo/face_recognizer.hpp#L233)

**Comment by Spring641** [comment]
> @Spring641, 请查看这个[接口](https://github.com/espressif/esp-dl/blob/d9493506707c0b68fa10447ec24380af6f19bb32/include/model_zoo/face_recognizer.hpp#L233)

好的多谢，还有一个问题请教一下，人脸识别录入ID断电没有保存，bool update_flash = true已经设置

**Comment by yehangyang** [comment]
@Spring641， 请问运行的是哪个示例？

**Comment by sun-xiangyu** [comment]
请尝试最新的esp-dl
