### ISSUE TITLE
ModuleNotFoundError: No module named 'calibrator' (AIV-520)

### ISSUE THREAD

**Issue by ifve** [espressif/esp-dl#93]
运行tools/quantization_tool/examples/example.py时报错：
 from calibrator import *
ModuleNotFoundError: No module named 'calibrator'
想请教这个缺失的包从哪里获取？
系统：ubuntu18.04
python: 3.7
esp-dl VERSION:  d9493506707c0b68fa10447ec24380af6f19bb32

**Comment by zdm-linux** [comment]
你好    这个问题你解决了么

**Comment by ali-espressif** [comment]
You can import the modules from here [dl-lib](https://github.com/espressif/esp-dl/tree/master/tools/quantization_tool) and import this into your project as a module.
