### ISSUE TITLE
Save enrolled face id in SD card instead of internal flash (AIV-522)

### ISSUE THREAD

**Issue by mike-2020** [espressif/esp-dl#94]
Hello,

I'd like to save enrolled face id in SD card, intead of internal flash (which has limited size). Is there a possible way to do it?

I checked class FaceRecognizer, but not found its implementation. So, it seems I cannot custermize the code by myself.

Thanks
Mike

**Comment by yehangyang** [comment]
Sorry, you cannot customize the code. We'll redesign the API for this situation,

**Comment by mike-2020** [comment]
Thanks. When will the new design be ready?

**Comment by MichaelDu9226** [comment]
@yehangyang When will the function of saving and loading face recognition models from SD cards be completed?

Or how can I modify the version of idf4.4 to ensure that the face model saved in flash can be reloaded after restarting.
Currently, our project is based on idf4.4, but it may not be possible to migrate to idf5.0 in the short term.

Relate this issue:
https://github.com/espressif/esp-who/issues/254

**Comment by MichaelDu9226** [comment]
@yehangyang When will the function of saving and loading face recognition models from SD cards be completed?

Or how can I modify the version of idf4.4 to ensure that the face model saved in flash can be reloaded after restarting.
Currently, our project is based on idf4.4, but it may not be possible to migrate to idf5.0 in the short term.

Relate this issue:
https://github.com/espressif/esp-who/issues/254

**Comment by sun-xiangyu** [comment]
Please try new esp-dl. Now you can save and load face id from flash or sd cards.
