### ISSUE TITLE
convert npys on Darwin (AIV-526)

### ISSUE THREAD

**Issue by 0624079** [espressif/esp-dl#95]
hello,
I flow the tutorial, and then I had a problem in convert npy files.
here is terminal log.

$ python ../tools/convert_tool/convert.py -i ./model/npy/ -n mnist_coefficient -o ./model
Not supported python == 3.9.10 on Darwin

My development environment as below:
1. MAC with M1 chip
2. VSCode with ESP-IDF extension
3. ESP-IDF v4.4
4. ESP-dl
5. ESP-EYE

plz give me some help, THX

**Comment by yehangyang** [comment]
So sorry, we didn't compile it for Mac OS yet. We'll add this later.
